tap "caskroom/cask"
tap "caskroom/fonts"

brew "fpp"
brew "git"
brew "heroku"
brew "httpie"
brew "mas"
brew "node"
brew "postgresql"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"

cask "evernote"
cask "flux"
cask "google-chrome"
cask "hipchat"
cask "iterm2"
cask "karabiner-elements"
cask "postman"
cask "slack"
cask "vlc"
cask "1password"

cask "font-source-code-pro"
cask "font-fira-code"
