# Environment Variables
export EDITOR="nvim"

# Aliases
alias d='docker'
alias dc='docker-compose'
alias g='git'
alias n='pnpm'
alias nx='pnpm dlx'
alias p='pulumi'
alias v='nvim'

# Not version-controlled configs and aliases
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Starship prompt
eval "$(starship init zsh)"

# Node environment management
eval "$(fnm env --use-on-cd)"

#direnv
eval "$(direnv hook zsh)"

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true
