# Set environment Variables
export EDITOR="nvim"

# Aliases
alias v='nvim'

# Not version-controlled configs and aliases
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Starship prompt
eval "$(starship init zsh)"

# Node version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

#direnv
eval "$(direnv hook zsh)"
